### ISSUE TITLE
How do i change this color...

### ISSUE THREAD

**Issue by jboss38** [redsigma/UPMetroSkin#1]
How do i change this color... 

![image](https://user-images.githubusercontent.com/6693379/31685717-4e4b8b0a-b384-11e7-9358-5ab82fc8768b.png)

Thanks.

**Comment by redsigma** [comment]
In steam.styles there is a part:
`		"GameItem_Running"
		{
			textcolor=game_run
			selectedtextcolor=game_run_selected
		}`
Change the textcolor to like textcolor="255 0 0 255" which stands for red in rgb color and 255 at the last is the opacity.
Sorry for not responding didn't got fully used to git as i only log in here for updating.Most of the time i am online on the steam and i frequently check the discussion there.

**Comment by jboss38** [comment]
Thanks for info.

It was for Game Download.

![image](https://user-images.githubusercontent.com/6693379/32975313-60de27c4-cc06-11e7-864a-ea443f054d20.png)

Here what i add : 
 
- In "colos.styles"
```
		game_update="255 171 0 200.6"
		game_SyncDecrypt="54 255 222 200"
```

- in "Steam.styles"

```
		"GameItem_Updating"
		{
			textcolor=game_update
			selectedtextcolor=game_run_selected
		}
		"GameItem_Updating:hover"
		{
			textcolor=game_update
		}

		"GameItem_Decrypting"
		{
			textcolor=game_SyncDecrypt
			selectedtextcolor=game_run_selected
		}
		"GameItem_Decrypting:hover"
		{
			textcolor=game_SyncDecrypt
		}

		"GameItem_Syncing"
		{
			textcolor=game_SyncDecrypt
			selectedtextcolor=game_run_selected
		}
		"GameItem_Syncing:hover"
		{
			textcolor=game_SyncDecrypt
		}

```
