### ISSUE TITLE
Running a mirror?

### ISSUE THREAD

**Issue by kotajacob** [redsigma/UPMetroSkin#2]
I run a little project called wal_steam that makes use of metro for steam and your patch for it. I was wondering if you would be opposed to me running a tiny mirror (just a minimal file server setup) with a zip file of your patch. Basically my program installs and themes the metro skin (with your patch added for linux support) and then colors it to match with your wallpaper's color scheme, you can check it out here if you're curious https://github.com/kotajacob/wal_steam

The current version is having problems though because downloading the files from github seems to fail a small percent of the time. Probably because github is blocking some automated downloads. One of the fixes of course will be to check the zips with an MD5 and redownload if needed, but in addition I think hosting an extra mirror with the patch would really help.

Sorry about spamming your issues page here. I tried emailing you, but it failed to send.

**Comment by henrikx** [comment]
Hey there. I'm the developer of an installer for this skin, which pulls files from this repo on GitHub and I haven't had this problem. I'm not sure how GitHub can block automated downloads though, as all HTTP traffic looks the same, apart from user-agent. Maybe try to add a user agent mimicking a browser and see if it still has this problem? As of mirroring it @RedSigma has to answer for that.

**Comment by kotajacob** [comment]
@henrikx Yea I actually updated it to use the firefox user-agent, but some downloads still were failing. I'm adding an md5 check of the zip (which will re-download on fail) to ensure that the file downloaded correctly. Still though I think a mirror would help as a backup if @redsigma is okay with that idea.

**Comment by redsigma** [comment]
Making a mirror will make the updating process more time consuming. There are already mirrors to MEGA.nz and dropbox.

**Comment by redsigma** [comment]
Btw the community disscusion page link url got changed so you can update your app descriptions with the new link.

**Comment by redsigma** [comment]
Also the reason why changing the font in custom.styles doesn't work it's cuz i added it in the debian.styles file found in resource/styles folder. 
PS: I should call that file linux.

**Comment by olback** [comment]
Just use this link?
[https://github.com/redsigma/UPMetroSkin/archive/master.zip](https://github.com/redsigma/UPMetroSkin/archive/master.zip)
