### ISSUE TITLE
New message number icon is offset.

### ISSUE THREAD

**Issue by Meowchestra** [redsigma/UPMetroSkin#25]

**Comment by GenesisFR** [comment]
Everything related to the new Steam chat is Valve's responsibility, it can't be skinned yet. You should report this on the Steam forums instead.

**Comment by GenesisFR** [comment]
Seems like Valve fixed it. This can be closed.

**Comment by go0d0ne** [comment]
yeah, fixed. this was never our issue, should have been closed right away.
