### ISSUE TITLE
No "change user" button in the drop down menu.

### ISSUE THREAD

**Issue by jrizzy93** [redsigma/UPMetroSkin#27]
There is no (or at least I haven't found it) "change account" button in the drop down menu/other menu that I can find

**Comment by GenesisFR** [comment]
I'm not using the latest version (4.2.4 + 9.1a) but it shouldn't be different on latest.

![image](https://user-images.githubusercontent.com/3614449/44624787-851b9080-a8c5-11e8-9015-31458e8fb293.png)

**Comment by go0d0ne** [comment]
also, new account button/avatar has it too.

**Comment by jrizzy93** [comment]
I mean, maybe i'm missing something, but I don't see the button https://imgur.com/a/65pCAg2

**Comment by go0d0ne** [comment]
obviously, since u r not even using the unofficial patch, judging from the screenie.

**Comment by jrizzy93** [comment]
I downloaded it from the Metro for Steam website... why else would I be here?

**Comment by go0d0ne** [comment]
this repository is a PATCH for Metro for Steam skin, not the vanilla metro skin itself.

**Comment by jrizzy93** [comment]
Ok, well my bad. I was just trying to report an issue

**Comment by redsigma** [comment]
Valve renamed some
