### ISSUE TITLE
[Linux] Topbar dropdown menus should be one or two pixels higher

### ISSUE THREAD

**Issue by KibaGasteiz** [redsigma/UPMetroSkin#31]
When you hover at Store, Library, Community, etc, there are some dropdown menus that you can use for entering different sections.
The problem is that those menus are somehow separated by a little gap and when you go down with the mouse the menus disappear, this doesn't happen in the Library section, but will happen in any "browser" page (Store, Community, etc). The skin is unusable right now on Linux because of this. Is it possible to move this dropdown menus higher somehow?

**Comment by redsigma** [comment]
Please update the uinavigatorpanel.layout file found in mainfiles/resources/layout and let me know if this issue got fixed.
I reverted the height of those buttons back to the default steam style and moved the accent line at the top so it's easy to see.

**Comment by KibaGasteiz** [comment]
Yes, with the new version it's working great. Didn't found any new issue.
EDIT: Feel free to close this issue.
