### ISSUE TITLE
[BUG] Notification in Steam

### ISSUE THREAD

**Issue by barbiehunter** [redsigma/UPMetroSkin#33]
I'm using the latest version of Github before you ask me if I'm using the latest.
![image](https://user-images.githubusercontent.com/38357837/63215509-c2f17480-c127-11e9-94ee-028d98038c0b.png)

**Comment by redsigma** [comment]
This it's a problem from valve not from the skin.

**Comment by Chaython** [comment]
> I'm using the latest version of Github before you ask me if I'm using the latest.
> ![image](https://user-images.githubusercontent.com/38357837/63215509-c2f17480-c127-11e9-94ee-028d98038c0b.png)

This has been an issue for a long time, use the friends/chat window to manage groups/friends [the notification counter there works]
![image](https://user-images.githubusercontent.com/6486343/68841500-f63d9400-0681-11ea-9938-b7fe9a6c079e.png)

**Comment by go0d0ne** [comment]
this is not a bug in skin... we should close this issue.
