### ISSUE TITLE
The new steam library

### ISSUE THREAD

**Issue by Chaython** [redsigma/UPMetroSkin#35]
https://store.steampowered.com/libraryupdate
Obviously completely breaks with this skin, yet they have not removed skin settings in the settings panel...

**Comment by PhantomGamers** [comment]
The library has already been fixed https://github.com/redsigma/UPMetroSkin/commit/212990410cc2ea6a6dcd71bcfbc9e06835f2c43d

It's not skinned yet, but skinning it will work similarly to the friends list, which on Windows goes through https://github.com/PhantomGamers/SteamFriendsPatcher

There's also a beta version of the patcher that already supports skinning the library available in the discord (I'll likely post it to github over the weekend)

**Comment by redsigma** [comment]
Please reopen if you have any other issues.

**Comment by Chaython** [comment]
This + that didn't do anything, just made the library flash on initial force check
Or clearing cache asked and then restarted steam as stated...
