### ISSUE TITLE
minor spacing issue in library

### ISSUE THREAD

**Issue by Stanzilla** [redsigma/UPMetroSkin#36]
Not sure if this can be corrected in the skin but there is not enough spacing on the left side here 

![image](https://user-images.githubusercontent.com/75278/65907777-49ef6900-e3c5-11e9-8647-15a00b0e31d6.png)

**Comment by EtienneBourque** [comment]
This issue might be out of date. Here is what I got with the current skin and Steam version:

![image](https://user-images.githubusercontent.com/50217898/68521355-3f4eac00-026e-11ea-88f2-28b939e31a68.png)

**Comment by Stanzilla** [comment]
Looks like https://github.com/redsigma/UPMetroSkin/pull/40 fixed it, nice! Might be still like 1px off or so but that looks way better
