### ISSUE TITLE
[BUG] Steam Crash

### ISSUE THREAD

**Issue by barbiehunter** [redsigma/UPMetroSkin#37]
I notice that my steam crashes daily, and I guess it has something to do with the theme. I sent my friend (who uses the old steam overlay) mine. I'm using the newer one during this time and we both have crash problems. I don't know if this is just a coincidence or not.

**Comment by sayandhar** [comment]
Can confirm the new Steam crashes daily with this theme on. If I change back to the default theme, it's fine.

**Comment by redsigma** [comment]
There are plenty of users who don't encounter any crashes. Post your system specs and any other steam logs you can find. Also if you receive any kind of message please make a screenshot of it.

Also if you're using linux start steam in terminal and when it crashes make a screenshot to the terminal so i can see the problem.

**Comment by sayandhar** [comment]
> There are plenty of users who don't encounter any crashes. Post your system specs and any other steam logs you can find. Also if you receive any kind of message please make a screenshot of it.

My laptop crashes almost every other time with "Steam is not responding". Specs:

- i5 8250u, 8GB DDR4, MX150 (Lenovo Ideapad 530s14inch)

My desktop however, doesnt crash as much. Specs:

- i3 6100, Zotac GTX 950 OC, 8GB DDR4, MSI H110M

**Comment by go0d0ne** [comment]
what exactly crashes (client itself, steam overlay process, game(s), other(s))?
a lot of these could be related to hw acceleration... do try to turn off all of hw acc and see if that helps.

in general, negative margins & paddings in client skin could introduce these issues, because hw acc would be more than a bit affected by these.

**Comment by sayandhar** [comment]
@go0d0ne The whole client crashes. While starting up, the client freezes, then pops the Windows 10 white titlebar & around the client with "(Not Responding)."

There's a new 5th Nov Steam Beta update where the comments say have fixed the crashing issues (could be related). I've yet to try on that.

**Comment by go0d0ne** [comment]
> There's a new 5th Nov Steam Beta update where the comments say have fixed the crashing issues (could be related). I've yet to try on that.

any feedback?

**Comment by sayandhar** [comment]
> > There's a new 5th Nov Steam Beta update where the comments say have fixed the crashing issues (could be related). I've yet to try on that.
> 
> any feedback?

I haven't had any client crashes so far.  I don't know if it was that update, some other update, or a system issue that fixed it.

**Comment by go0d0ne** [comment]
> I haven't had any client crashes so far. I don't know if it was that update, some other update, or a system issue that fixed it.

I guess we can close this issue then.

**Comment by redsigma** [comment]
Gonna close this for now. If the problem appears again feel free to re-open it
