### ISSUE TITLE
Add view navigation tab so you can access hidden games.

### ISSUE THREAD

**Issue by mibby** [redsigma/UPMetroSkin#39]

**Comment by redsigma** [comment]
Valve removed the hidden games tab. The skin cannot add new stuff, it can only skin existing stuff. A workaround is to make a new category, add all the games in this category, then remove only the games you dont want to be hidden.

**Comment by mibby** [comment]
@redsigma Valve did not remove the hidden games tab. It is no longer accessible from the main library but without the skin enabled, you can access it from View > Hidden Games tab at the top.

Metro hides the top bar options, making it impossible to access hidden games.
