### ISSUE TITLE
Lag in library

### ISSUE THREAD

**Issue by MoneyAllDay** [redsigma/UPMetroSkin#44]
I'm not sure if it's just me but i get some lag when i'm in the library, more specifically on top of the page of any selected game.

[Example](https://youtu.be/ZewyyG_yhS8)

**Comment by GenesisFR** [comment]
Do you have hardware acceleration enabled? If not, try to enable it through "Settings -> Interface -> Enable GPU accelerated rendering in web views".

**Comment by MoneyAllDay** [comment]
That was exactly it. I had disabled "...GPU accelerated rendering..." some time ago because in game the overlay sometimes would be just [black boxes](https://i.imgur.com/J9qD3YM.png), which is a steam problem not MetroSkin.

Thank you.
