### ISSUE TITLE
Checkbox BUG

### ISSUE THREAD

**Issue by cheneylee5752** [redsigma/UPMetroSkin#48]
![1](https://user-images.githubusercontent.com/55355429/85946652-63cfd380-b978-11ea-8600-32dca79c6430.png)

**Comment by PhantomGamers** [comment]
This happens when you install the patch without installing the main skin. Install the main metro skin first and then install the patch over it.

**Comment by redsigma** [comment]
This is not a bug. The patch doesn't contain all the images because they are too many. @cheneylee5752  like @PhantomGamers  said , install the official skin and then apply the patch on top of it and replace all.
