### ISSUE TITLE
Bandwith limit

### ISSUE THREAD

**Issue by myniocha** [redsigma/UPMetroSkin#49]
I installed the metro skin first and then the unofficial patch like always and I am experiencing this issue now. It used to work perfectly fine before, but now I can't figure out what's the problem. All other tabs are okay, but this one only. The tab's called "Downloading"

![steam_xIHSjqcgBx](https://user-images.githubusercontent.com/71589504/93708933-879b5380-fb3a-11ea-909a-b921dda7f069.png)

**Comment by myniocha** [comment]
As of today, the problem seems to be resolved, thanks to Steam I guess? Maybe that was because of some sort of font issue?
![image](https://user-images.githubusercontent.com/71589504/96015750-3421da00-0e48-11eb-9473-52a9cbe225f4.png)

**Comment by Glaived** [comment]
Not solve for me ¯\_(ツ)_/¯
