### ISSUE TITLE
PixelVision 2 overlay while in game (Request)

### ISSUE THREAD

**Issue by Peppyy** [redsigma/UPMetroSkin#52]
![image](https://user-images.githubusercontent.com/24255543/96504259-5e123c80-124c-11eb-81e2-aca60a252ac0.png)
![image](https://user-images.githubusercontent.com/24255543/96504273-62d6f080-124c-11eb-971d-c93762681b8d.png)

**Comment by redsigma** [comment]
This extra has been added as of this commit 50faa14d1054079f732a9f7a52f47ae4155a90dc
It has some small changes to match the metro skin. Also the compact overlay has some changes so it works on lower resolutions down to 640x480
