### ISSUE TITLE
A sentence is missing in Settings -> Interface

### ISSUE THREAD

**Issue by GenesisFR** [redsigma/UPMetroSkin#53]
Vanilla
![image](https://user-images.githubusercontent.com/3614449/119263782-736a9300-bbae-11eb-8204-5da6f41f2feb.png)
Metro
![image](https://user-images.githubusercontent.com/3614449/119263893-ee33ae00-bbae-11eb-8deb-b0b045cca736.png)

I was using https://github.com/redsigma/UPMetroSkin/commit/fdf68b6b0b58a1ee9a8ad3aa1666403b3f79f88f but I even tried on the latest revision and the issue is still there.

**Comment by redsigma** [comment]
That was done on purpose because the font size is bigger than in vanilla metro. A workaround is to increase the height of the whole settings panel which would give more space to add the text and also make the panel more ugly
