### ISSUE TITLE
Support for new chat system

### ISSUE THREAD

**Issue by levrik** [redsigma/UPMetroSkin#7]
The new chat system (and corresponding UI) is in beta at the moment.
Is support for this planned?

**Comment by jonyroda97** [comment]
They released a version with some fixes but the chat has no skin for the moment:
https://mega.nz/#F!3ItGCJ4J!on8WV7Yr_JahFjAD8fVWHg

Check the Discord Server. They announce new versions and updates there.
https://discord.gg/015OTigbS9wyJlBDP
