### ISSUE TITLE
can't seem to able to use the skin

### ISSUE THREAD

**Issue by Welnnys** [redsigma/UPMetroSkin#72]
![image](https://user-images.githubusercontent.com/52232769/229295081-8c8bc19f-2ca7-4566-aac9-2120246c9fa9.png)

I put it inside my skins folder but it doesn't work, did I download the wrong thing or do I need to use it with the old skin or what exactly?

**Comment by redsigma** [comment]
please use this https://github.com/henrikx/metroskininstaller/releases

**Comment by Welnnys** [comment]
I just used the installer as you told me to and restarted my steam and it looks like this 
![image](https://user-images.githubusercontent.com/52232769/229295598-45312939-ac5a-4a62-a5d0-7079ea415919.png)

**Comment by redsigma** [comment]
after you use the installer go to Settings > Interface > Select metroskin from the drobdown

The store page being black doesnt have anything to do with the skin. Keep refreshing or switch to library and then back to store.

**Comment by Welnnys** [comment]
yea now it works, thanks, have a good one

**Comment by Welnnys** [comment]
Is there any way I can preview each extra feature instead it downloading it over and over 😆

**Comment by redsigma** [comment]
for now the only way is to download this github repo and check the preview.png images in each folder. You can also view them directly from here , in the browser so no need actually download it.

**Comment by Welnnys** [comment]
Is there an extra which hides my username on the top right corner?

**Comment by redsigma** [comment]
the remastered extra hides the dropdown which has your username
