### ISSUE TITLE
Friends not rendered correctly in the in-game overlay

### ISSUE THREAD

**Issue by Katzenwerfer** [redsigma/UPMetroSkin#73]
I am currently using the `Default Overlay Style`, which seems to have a bug where the friends section is not rendered correctly.

![image](https://user-images.githubusercontent.com/53267697/230546678-7ed5d67c-7341-4903-96ea-7bd19804c517.png)

I'm unsure, but I think it might also affect the other overlay styles except for the one that comes with the vanilla unmodified patch.

**Comment by redsigma** [comment]
Does this work in the default steam ?

**Comment by Katzenwerfer** [comment]
Yep, it is displayed correctly.

![image](https://user-images.githubusercontent.com/53267697/230547917-db21dd0f-0b98-46b6-b6d8-df008e0a9d20.png)

**Comment by Katzenwerfer** [comment]
I am still trying to narrow down the issue because I am kind of unsure if it is a problem of the files themselves or resources messing between styles, or maybe something else entirely.

**Comment by redsigma** [comment]
there is an extra called Friends Avatars in the Overlay folder. Could you try to apply that and see if it fixes the problem

**Comment by redsigma** [comment]
have you fixed the problem @Katzenwerfer  ?

**Comment by Katzenwerfer** [comment]
Seemingly, it was an issue with the steam client on its own. Doesn't occur anymore, so I guess this can be closed now. I'll still be checking if it happens again.
