### ISSUE TITLE
Issues installing latest fixes

### ISSUE THREAD

**Issue by ChickenCranberry** [redsigma/UPMetroSkin#74]
Hello, I'm still having issues with my Metro for Steam Skin, which was and still is an issue of Steam entering full screen or causing me, the user to be unable to see the tabs which would include, Store, Library. Community, User, Notifications. Active Friends, plus more.

If there's a solution such as a video or instruction on how to fix or solve this issue then I would like it, please.

![Screenshot (342)](https://user-images.githubusercontent.com/118373610/233792442-e36d3d15-3657-43e8-9ffa-abe1dde453d2.png)

**Comment by redsigma** [comment]
please reinstall using the metro auto installer 

https://github.com/henrikx/metroskininstaller/releases
